import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Route, Switch, Link, useLocation, Router as WouterRouter } from 'wouter';
import {
  Activity, AlertTriangle, ArrowDownLeft, ArrowUpRight, BarChart3, Bell, Boxes, BriefcaseMedical,
  CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardList,
  Clock3, FileBarChart2, FileClock, FilePlus2, Filter, HeartPulse, LayoutDashboard,
  ListFilter, Menu, MoreHorizontal, Package, PackageCheck, Plus, Search, Settings, ShieldCheck,
  ShoppingBag, ShoppingCart, SlidersHorizontal, Sparkles, Stethoscope, Trash2, Truck, Users, X,
} from 'lucide-react';
import './index.css';

type Product = { id:string; sku:string; name:string; genericName:string; brand:string; category:string; dosageForm:string; strength:string; unit:string; barcode:string; batchNumber:string; supplierId:string; purchasePrice:number; sellingPrice:number; quantity:number; minStock:number; maxStock:number; manufactureDate:string; expiryDate:string; prescriptionRequired:boolean; status:string; description:string };
type Customer = { id:string; name:string; phone:string; email:string; address:string; loyalty:number; createdAt:string };
type Supplier = { id:string; name:string; contact:string; phone:string; email:string; address:string; terms:string };
type Staff = { id:string; name:string; role:string; phone:string; email:string; status:string };
type Line = { productId:string; name:string; qty:number; cost:number; price:number };
type Sale = { id:string; invoice:string; customerId:string; customer:string; timestamp:string; payment:string; status:string; items:Line[]; total:number };
type Purchase = { id:string; invoice:string; supplierId:string; supplier:string; date:string; status:string; items:Line[]; total:number };
type Movement = { id:string; productId:string; product:string; delta:number; kind:string; reference:string; timestamp:string; note:string };
type Store = { products:Product[]; customers:Customer[]; suppliers:Supplier[]; staff:Staff[]; sales:Sale[]; purchases:Purchase[]; movements:Movement[]; settings:{pharmacyName:string; currency:string; tax:number; lowStock:number; expiryDays:number; address:string; phone:string} };

const KEY='pharmacy-desk-v1';
const localDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const today=()=>localDate(new Date());
const days=(n:number)=>{const date=new Date();date.setDate(date.getDate()+n);return localDate(date)};
const daysUntilExpiry=(value:string)=>{const [year,month,day]=value.split('-').map(Number);const now=new Date();return Math.round((Date.UTC(year,month-1,day)-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)};
const id=()=>Math.random().toString(36).slice(2,10);
const seed:Store={
 products:[
  {id:'p1',sku:'MED-001',name:'Amoxicillin 500mg',genericName:'Amoxicillin',brand:'Amoxil',category:'Antibiotics',dosageForm:'Capsule',strength:'500 mg',unit:'capsule',barcode:'8901234567012',batchNumber:'AMX-24-091',supplierId:'s1',purchasePrice:0.24,sellingPrice:0.55,quantity:184,minStock:60,maxStock:500,manufactureDate:'2024-11-01',expiryDate:days(22),prescriptionRequired:true,status:'Active',description:'Broad-spectrum antibiotic. Store below 25°C.'},
  {id:'p2',sku:'MED-002',name:'Paracetamol 500mg',genericName:'Acetaminophen',brand:'Panadol',category:'Pain Relief',dosageForm:'Tablet',strength:'500 mg',unit:'tablet',barcode:'8901234567029',batchNumber:'PAR-25-104',supplierId:'s2',purchasePrice:0.04,sellingPrice:0.15,quantity:38,minStock:80,maxStock:700,manufactureDate:'2025-01-17',expiryDate:days(490),prescriptionRequired:false,status:'Active',description:'Analgesic and antipyretic.'},
  {id:'p3',sku:'MED-003',name:'Vitamin D3 1000 IU',genericName:'Cholecalciferol',brand:'D-Sure',category:'Vitamins',dosageForm:'Softgel',strength:'1000 IU',unit:'softgel',barcode:'8901234567036',batchNumber:'VD3-25-018',supplierId:'s1',purchasePrice:0.12,sellingPrice:0.38,quantity:124,minStock:40,maxStock:300,manufactureDate:'2025-02-09',expiryDate:days(680),prescriptionRequired:false,status:'Active',description:'Daily vitamin D supplement.'},
  {id:'p4',sku:'MED-004',name:'Cetirizine 10mg',genericName:'Cetirizine',brand:'Zyrtec',category:'Cold & Flu',dosageForm:'Tablet',strength:'10 mg',unit:'tablet',barcode:'8901234567043',batchNumber:'CET-24-33A',supplierId:'s2',purchasePrice:0.08,sellingPrice:0.28,quantity:7,minStock:35,maxStock:240,manufactureDate:'2024-08-20',expiryDate:days(95),prescriptionRequired:false,status:'Active',description:'Non-drowsy antihistamine.'},
  {id:'p5',sku:'MED-005',name:'Metformin 500mg',genericName:'Metformin HCl',brand:'Glucophage',category:'Diabetes',dosageForm:'Tablet',strength:'500 mg',unit:'tablet',barcode:'8901234567050',batchNumber:'MET-25-026',supplierId:'s3',purchasePrice:0.07,sellingPrice:0.22,quantity:0,minStock:50,maxStock:400,manufactureDate:'2025-01-04',expiryDate:days(330),prescriptionRequired:true,status:'Active',description:'Oral antihyperglycemic medicine.'},
  {id:'p6',sku:'MED-006',name:'Amlodipine 5mg',genericName:'Amlodipine',brand:'Norvasc',category:'Cardiovascular',dosageForm:'Tablet',strength:'5 mg',unit:'tablet',barcode:'8901234567067',batchNumber:'AML-24-877',supplierId:'s3',purchasePrice:0.11,sellingPrice:0.34,quantity:92,minStock:45,maxStock:350,manufactureDate:'2024-12-05',expiryDate:days(38),prescriptionRequired:true,status:'Active',description:'Calcium channel blocker.'},
  {id:'p7',sku:'MED-007',name:'Hydrocortisone 1% cream',genericName:'Hydrocortisone',brand:'Cortaid',category:'Dermatology',dosageForm:'Cream',strength:'1%',unit:'tube',barcode:'8901234567074',batchNumber:'HYD-24-611',supplierId:'s2',purchasePrice:1.85,sellingPrice:3.75,quantity:23,minStock:20,maxStock:100,manufactureDate:'2024-10-12',expiryDate:days(14),prescriptionRequired:false,status:'Active',description:'Topical relief for mild irritation.'},
  {id:'p8',sku:'MED-008',name:'Sterile gauze pads',genericName:'Cotton gauze',brand:'MedSoft',category:'First Aid',dosageForm:'Dressing',strength:'10 × 10 cm',unit:'pack',barcode:'8901234567081',batchNumber:'GAU-25-105',supplierId:'s1',purchasePrice:1.1,sellingPrice:2.4,quantity:68,minStock:25,maxStock:160,manufactureDate:'2025-03-03',expiryDate:days(900),prescriptionRequired:false,status:'Active',description:'Sterile 10-count dressing pack.'},
  {id:'p9',sku:'MED-009',name:'Saline eye drops',genericName:'Sodium chloride',brand:'ClearVue',category:'Personal Care',dosageForm:'Eye drops',strength:'0.9%',unit:'bottle',barcode:'8901234567098',batchNumber:'SAL-25-014',supplierId:'s1',purchasePrice:1.1,sellingPrice:2.6,quantity:14,minStock:10,maxStock:80,manufactureDate:'2024-06-12',expiryDate:days(-3),prescriptionRequired:false,status:'Active',description:'Sterile saline drops. Expired batch flagged for removal.'}
 ],
 customers:[
  {id:'c1',name:'Maya Chen',phone:'+1 (415) 555-0182',email:'maya.chen@email.com',address:'Pacific Heights',loyalty:218,createdAt:days(-142)},
  {id:'c2',name:'David Okafor',phone:'+1 (415) 555-0116',email:'d.okafor@email.com',address:'Hayes Valley',loyalty:96,createdAt:days(-67)},
  {id:'c3',name:'Rosa Martinez',phone:'+1 (415) 555-0144',email:'rosa.m@email.com',address:'Lower Haight',loyalty:340,createdAt:days(-230)},
  {id:'c4',name:'Walk-in customer',phone:'—',email:'—',address:'—',loyalty:0,createdAt:today()}
 ],
 suppliers:[
  {id:'s1',name:'Northstar Medical Supply',contact:'Elena Morris',phone:'+1 (800) 555-0214',email:'orders@northstarmed.co',address:'Oakland, CA',terms:'Net 30'},
  {id:'s2',name:'Crescent Pharma Wholesale',contact:'Samir Patel',phone:'+1 (800) 555-0390',email:'hello@crescentpharma.co',address:'San Jose, CA',terms:'Net 45'},
  {id:'s3',name:'Meridian Therapeutics',contact:'Nina Williams',phone:'+1 (800) 555-0167',email:'supply@meridianrx.co',address:'Sacramento, CA',terms:'Net 30'}
 ],
 staff:[
  {id:'u1',name:'Olivia Reyes',role:'Pharmacist in charge',phone:'+1 (415) 555-0100',email:'olivia@harborpharmacy.com',status:'On shift'},
  {id:'u2',name:'Marcus Bell',role:'Pharmacy technician',phone:'+1 (415) 555-0101',email:'marcus@harborpharmacy.com',status:'On shift'},
  {id:'u3',name:'Priya Shah',role:'Pharmacy technician',phone:'+1 (415) 555-0102',email:'priya@harborpharmacy.com',status:'Off shift'}
 ],
 sales:[
  {id:'sale1',invoice:'RX-2025-0418',customerId:'c1',customer:'Maya Chen',timestamp:new Date().toISOString(),payment:'Card',status:'Completed',items:[{productId:'p2',name:'Paracetamol 500mg',qty:2,cost:.04,price:.15},{productId:'p3',name:'Vitamin D3 1000 IU',qty:1,cost:.12,price:.38}],total:.68},
  {id:'sale2',invoice:'RX-2025-0417',customerId:'c2',customer:'David Okafor',timestamp:new Date(Date.now()-86400000).toISOString(),payment:'Cash',status:'Completed',items:[{productId:'p1',name:'Amoxicillin 500mg',qty:10,cost:.24,price:.55}],total:5.5},
  {id:'sale3',invoice:'RX-2025-0416',customerId:'c3',customer:'Rosa Martinez',timestamp:new Date(Date.now()-2*86400000).toISOString(),payment:'Card',status:'Completed',items:[{productId:'p6',name:'Amlodipine 5mg',qty:30,cost:.11,price:.34}],total:10.2},
  {id:'sale4',invoice:'RX-2025-0415',customerId:'c4',customer:'Walk-in customer',timestamp:new Date(Date.now()-3*86400000).toISOString(),payment:'Cash',status:'Completed',items:[{productId:'p8',name:'Sterile gauze pads',qty:2,cost:1.1,price:2.4}],total:4.8},
 ],
 purchases:[
  {id:'po1',invoice:'PO-2025-0182',supplierId:'s1',supplier:'Northstar Medical Supply',date:days(-2),status:'Received',items:[{productId:'p3',name:'Vitamin D3 1000 IU',qty:120,cost:.12,price:.38}],total:14.4},
  {id:'po2',invoice:'PO-2025-0181',supplierId:'s2',supplier:'Crescent Pharma Wholesale',date:days(-8),status:'Received',items:[{productId:'p2',name:'Paracetamol 500mg',qty:300,cost:.04,price:.15}],total:12}
 ],
 movements:[
  {id:'m1',productId:'p2',product:'Paracetamol 500mg',delta:-2,kind:'Sale',reference:'RX-2025-0418',timestamp:new Date().toISOString(),note:'Point of sale'},
  {id:'m2',productId:'p3',product:'Vitamin D3 1000 IU',delta:120,kind:'Purchase received',reference:'PO-2025-0182',timestamp:new Date(Date.now()-2*86400000).toISOString(),note:'Supplier delivery'},
  {id:'m3',productId:'p1',product:'Amoxicillin 500mg',delta:-10,kind:'Sale',reference:'RX-2025-0417',timestamp:new Date(Date.now()-86400000).toISOString(),note:'Point of sale'}
 ],
 settings:{pharmacyName:'Harbor & Pine Pharmacy',currency:'USD',tax:0,lowStock:30,expiryDays:90,address:'1847 Clement Street, San Francisco, CA',phone:'+1 (415) 555-0140'}
};

function readStore():{value:Store; warning:string; writable:boolean} {
 try {
  const raw=localStorage.getItem(KEY);
  if(!raw)return {value:seed,warning:'',writable:true};
  const parsed=JSON.parse(raw);
  if(parsed.version!==1||!parsed.data||!Array.isArray(parsed.data.products)) return {value:seed,warning:'Saved pharmacy data could not be read. Your original browser data has been preserved; changes will not overwrite it.',writable:false};
  return {value:parsed.data as Store,warning:'',writable:true};
 } catch { return {value:seed,warning:'Local storage is unavailable or contains unreadable data. Existing browser data has not been changed; changes in this session may not persist.',writable:false}; }
}
const money=(n:number,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:2}).format(n||0);
const dateLabel=(value:string)=>value?new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
const statusOf=(p:Product,expiryDays=90)=>p.quantity<=0?'Out of stock':daysUntilExpiry(p.expiryDate)<0?'Expired':p.quantity<=p.minStock?'Low stock':daysUntilExpiry(p.expiryDate)<=expiryDays?'Expiring soon':'In stock';
const nav=[
 {href:'/',label:'Overview',icon:LayoutDashboard,group:'WORKSPACE'},
 {href:'/sales',label:'Sales & POS',icon:ShoppingCart,group:'WORKSPACE'},
 {href:'/products',label:'Medicines',icon:Package,group:'WORKSPACE'},
 {href:'/inventory',label:'Inventory',icon:Boxes,group:'WORKSPACE'},
 {href:'/purchases',label:'Purchases',icon:Truck,group:'WORKSPACE'},
 {href:'/customers',label:'Customers',icon:Users,group:'RELATIONSHIPS'},
 {href:'/suppliers',label:'Suppliers',icon:BriefcaseMedical,group:'RELATIONSHIPS'},
 {href:'/reports',label:'Reports',icon:FileBarChart2,group:'INSIGHTS'},
 {href:'/staff',label:'Team',icon:ShieldCheck,group:'INSIGHTS'},
 {href:'/settings',label:'Settings',icon:Settings,group:'INSIGHTS'}
];
const titleFor=(path:string)=>nav.find(n=>n.href===path)?.label||'Overview';

function PharmacyApp(){
 const initial=useMemo(readStore,[]);
 const [store,setStore]=useState<Store>(initial.value);
 const [warning,setWarning]=useState(initial.warning);
 const [writable,setWritable]=useState(initial.writable);
 const [path]=useLocation();
 const [collapsed,setCollapsed]=useState(false);
 const [drawer,setDrawer]=useState(false);
 const [toast,setToast]=useState('');
 useEffect(()=>{if(!writable)return;try{localStorage.setItem(KEY,JSON.stringify({version:1,data:store}));}catch{setWarning('Could not save to browser storage. Your current session data is still available.');setWritable(false);}},[store,writable]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t);},[toast]);
 const notify=(s:string)=>setToast(s);
 const patch=(key:keyof Store,records:any)=>setStore(s=>({...s,[key]:typeof records==='function'?records(s[key]):records}));
 const move=(product:Product,delta:number,kind:string,reference:string,note:string)=>patch('movements',(items:Movement[])=>[{id:id(),productId:product.id,product:product.name,delta,kind,reference,timestamp:new Date().toISOString(),note},...items]);
 const saveProduct=(p:Product,editing:boolean)=>{const old=store.products.find(x=>x.id===p.id);patch('products',editing?store.products.map(x=>x.id===p.id?p:x):[p,...store.products]);if(!editing&&p.quantity)move(p,p.quantity,'Initial stock',p.sku,'Opening balance');if(editing&&old&&p.quantity!==old.quantity)move(p,p.quantity-old.quantity,'Adjustment','Manual','Edited product quantity');notify(editing?'Medicine updated':'Medicine added');};
 const saveEntity=(key:'customers'|'suppliers'|'staff',item:any,editing:boolean)=>{patch(key,editing?(store[key] as any[]).map(x=>x.id===item.id?item:x):[item,...store[key]]);notify(editing?'Record updated':'Record added');};
 const deleteRecord=(key:keyof Store,item:any)=>{if(!window.confirm(`Delete ${item.name||item.invoice||'this record'}? This action cannot be undone.`))return;patch(key,(store[key] as any[]).filter(x=>x.id!==item.id));notify('Record deleted');};
 const completeSale=(cart:Line[],customerId:string,payment:string)=>{
  if(!cart.length)return;
  const bad=cart.find(line=>(store.products.find(p=>p.id===line.productId)?.quantity||0)<line.qty);
  if(bad){notify(`${bad.name} no longer has enough stock`);return;}
  const customer=store.customers.find(c=>c.id===customerId)||store.customers[store.customers.length-1];
  const sale:Sale={id:id(),invoice:`RX-${new Date().getFullYear()}-${String(store.sales.length+418).padStart(4,'0')}`,customerId:customer.id,customer:customer.name,timestamp:new Date().toISOString(),payment,status:'Completed',items:cart,total:cart.reduce((sum,x)=>sum+x.qty*x.price,0)};
  patch('sales',[sale,...store.sales]);
  for(const line of cart){const p=store.products.find(x=>x.id===line.productId);if(p){patch('products',(items:Product[])=>items.map(x=>x.id===p.id?{...x,quantity:x.quantity-line.qty}:x));move(p,-line.qty,'Sale',sale.invoice,'Point of sale');}}
  notify(`Sale ${sale.invoice} completed`);
 };
 const reverseSale=(sale:Sale)=>{if(sale.status!=='Completed')return;if(!window.confirm(`Reverse ${sale.invoice}? Stock will be restored and this sale marked as reversed.`))return;patch('sales',(items:Sale[])=>items.map(x=>x.id===sale.id?{...x,status:'Reversed'}:x));sale.items.forEach(line=>{const p=store.products.find(x=>x.id===line.productId);if(p){patch('products',(items:Product[])=>items.map(x=>x.id===p.id?{...x,quantity:x.quantity+line.qty}:x));move(p,line.qty,'Sale reversed',sale.invoice,'Stock restored after reversal');}});notify('Sale reversed and stock restored');};
 const receivePurchase=(purchase:Purchase)=>{if(purchase.status==='Received')return;patch('purchases',(items:Purchase[])=>items.map(x=>x.id===purchase.id?{...x,status:'Received'}:x));purchase.items.forEach(line=>{const p=store.products.find(x=>x.id===line.productId);if(p){patch('products',(items:Product[])=>items.map(x=>x.id===p.id?{...x,quantity:x.quantity+line.qty}:x));move(p,line.qty,'Purchase received',purchase.invoice,'Supplier order received');}});notify(`${purchase.invoice} received; stock updated`);};
  const adjustStock=(product:Product,delta:number,note:string)=>{const applied=Math.max(-product.quantity,delta);if(!applied){notify('Stock is already at zero');return;}patch('products',(items:Product[])=>items.map(p=>p.id===product.id?{...p,quantity:p.quantity+applied}:p));move(product,applied,'Adjustment','Manual',note);notify(applied===delta?'Stock adjustment recorded':`Stock reduced by ${Math.abs(applied)} units; quantity cannot go below zero`);};
 const shared={store,patch,saveProduct,saveEntity,deleteRecord,completeSale,reverseSale,receivePurchase,adjustStock,notify};
 return <div className="app-shell">
   {drawer&&<div className="drawer-scrim" onClick={()=>setDrawer(false)} />}
   <aside className={`sidebar ${collapsed?'is-collapsed':''} ${drawer?'mobile-open':''}`}>
    <Link href="/" className="brand-lockup" onClick={()=>setDrawer(false)}><span className="brand-mark"><HeartPulse size={19}/></span>{!collapsed&&<span className="brand-copy"><b>Harbor <em>&</em> Pine</b><small>PHARMACY DESK</small></span>}</Link>
    <div className="sidebar-scroll">{['WORKSPACE','RELATIONSHIPS','INSIGHTS'].map(group=><div className="nav-group" key={group}><div className="nav-label">{!collapsed&&group}</div>{nav.filter(n=>n.group===group).map(item=><Link onClick={()=>setDrawer(false)} key={item.href} href={item.href} className={`nav-link ${path===item.href?'active':''}`} title={collapsed?item.label:undefined} data-testid={`link-nav-${item.label.toLowerCase().replaceAll(' ','-')}`}><item.icon size={17}/>{!collapsed&&<span>{item.label}</span>}{item.href==='/inventory'&&!collapsed&&store.products.filter(p=>statusOf(p,store.settings.expiryDays)==='Low stock'||p.quantity===0).length>0&&<i>{store.products.filter(p=>p.quantity<=p.minStock).length}</i>}</Link>)}</div>)}</div>
    {!collapsed&&<div className="sidebar-foot"><div className="open-pill"><span className="pulse"></span> Store open <span>·</span> 9:00–21:00</div><button className="profile" onClick={()=>notify('Signed in locally as Olivia Reyes')}><span className="avatar">OR</span><span className="profile-meta"><b>Olivia Reyes</b><small>Pharmacist in charge</small></span><MoreHorizontal size={18}/></button></div>}
   </aside>
   <main className={`main-area ${collapsed?'wide':''}`}>
    <header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setDrawer(true)} aria-label="Open menu"><Menu size={19}/></button><button className="icon-button collapse-btn" onClick={()=>setCollapsed(v=>!v)} aria-label="Collapse navigation"><ChevronLeft size={18}/></button><div className="crumb"><span>Harbor & Pine</span><ChevronRight size={14}/><strong>{titleFor(path)}</strong></div><div className="top-actions"><span className="today-label"><CalendarDays size={15}/>{new Date().toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</span><button className="icon-button bell-button" onClick={()=>notify('You’re all caught up')} aria-label="Notifications"><Bell size={17}/><i/></button><span className="top-avatar">OR</span></div></header>
    {warning&&<div className="storage-alert"><AlertTriangle size={17}/><span>{warning}</span><button onClick={()=>setWarning('')} aria-label="Dismiss"><X size={15}/></button></div>}
    <div className="page-content"><Switch>
      <Route path="/"><Dashboard {...shared}/></Route>
      <Route path="/sales"><Sales {...shared}/></Route>
      <Route path="/products"><Products {...shared}/></Route>
      <Route path="/inventory"><Inventory {...shared}/></Route>
      <Route path="/purchases"><Purchases {...shared}/></Route>
      <Route path="/customers"><Directory {...shared} kind="customers"/></Route>
      <Route path="/suppliers"><Directory {...shared} kind="suppliers"/></Route>
      <Route path="/reports"><Reports {...shared}/></Route>
      <Route path="/staff"><Directory {...shared} kind="staff"/></Route>
      <Route path="/settings"><SettingsPage {...shared}/></Route>
      <Route><NotFound/></Route>
    </Switch></div>
   </main>
   {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
  </div>;
}

type Shared={store:Store;patch:(key:keyof Store,records:any)=>void;saveProduct:(p:Product,e:boolean)=>void;saveEntity:(k:'customers'|'suppliers'|'staff',i:any,e:boolean)=>void;deleteRecord:(key:keyof Store,item:any)=>void;completeSale:(c:Line[],id:string,p:string)=>void;reverseSale:(s:Sale)=>void;receivePurchase:(p:Purchase)=>void;adjustStock:(p:Product,d:number,n:string)=>void;notify:(s:string)=>void};
function Heading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action&&<div className="heading-action">{action}</div>}</div>}
function Button({children,onClick,kind='primary',icon}:{children:ReactNode;onClick:()=>void;kind?:'primary'|'quiet'|'danger'|'outline';icon?:ReactNode}){return <button type="button" onClick={onClick} className={`button ${kind}`}>{icon}{children}</button>}
function Stat({label,value,detail,icon:Icon,accent='sage'}:{label:string;value:string;detail:string;icon:any;accent?:string}){return <div className={`stat-card ${accent}`}><div className="stat-top"><span>{label}</span><span className="stat-icon"><Icon size={17}/></span></div><strong>{value}</strong><small>{detail}</small></div>}
function Panel({title,sub,action,children,className=''}:{title:string;sub?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
function Empty({title,sub,action}:{title:string;sub:string;action?:ReactNode}){return <div className="empty-state"><span className="empty-icon"><Package size={21}/></span><b>{title}</b><p>{sub}</p>{action}</div>}
function SearchBox({value,onChange,placeholder='Search records...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="searchbox"><Search size={16}/><input data-testid="input-search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange('')} aria-label="Clear search"><X size={14}/></button>}</label>}
function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function currency(store:Store,n:number){return money(n,store.settings.currency);}
function Dashboard({store}:Shared){
 const [range,setRange]=useState(7);
 const valid=store.sales.filter(s=>s.status==='Completed');
 const start=new Date();start.setHours(0,0,0,0);
 const todaySales=valid.filter(s=>new Date(s.timestamp)>=start);
 const salesRange=range===1?valid.filter(s=>new Date(s.timestamp)>=start):valid.filter(s=>(Date.now()-new Date(s.timestamp).getTime())/86400000<range);
 const daysCount=range===1?12:range;
 const chart=Array.from({length:daysCount},(_,i)=>{if(range===1){const hour=i+9;const total=salesRange.filter(s=>new Date(s.timestamp).getHours()===hour).reduce((a,s)=>a+s.total,0);return {label:hour===12?'12p':hour>12?`${hour-12}p`:`${hour}a`,total,date:new Date()}}const date=new Date();date.setDate(date.getDate()-(daysCount-1-i));const key=date.toDateString();const total=salesRange.filter(s=>new Date(s.timestamp).toDateString()===key).reduce((a,s)=>a+s.total,0);return {label:date.toLocaleDateString('en-US',{weekday:'short'}),total,date};});
 const chartMax=Math.max(1,...chart.map(x=>x.total));
 const sold=new Map<string,{qty:number;revenue:number}>();valid.forEach(s=>s.items.forEach(i=>{const v=sold.get(i.productId)||{qty:0,revenue:0};v.qty+=i.qty;v.revenue+=i.qty*i.price;sold.set(i.productId,v);}));
 const top=[...sold.entries()].map(([pid,v])=>({product:store.products.find(p=>p.id===pid)?.name||'Removed medicine',...v})).sort((a,b)=>b.qty-a.qty).slice(0,4);
 const low=store.products.filter(p=>p.quantity<=p.minStock);
  const expiring=store.products.filter(p=>{const d=daysUntilExpiry(p.expiryDate);return p.quantity>0&&d>=0&&d<=store.settings.expiryDays;});
  const expired=store.products.filter(p=>p.quantity>0&&daysUntilExpiry(p.expiryDate)<0);
 const inventoryValue=store.products.reduce((n,p)=>n+p.quantity*p.purchasePrice,0);
  return <><Heading eyebrow="PHARMACY OVERVIEW" title="Good morning, Olivia" description="Here’s the pulse of your pharmacy today." action={<span className="live-date"><span className="pulse"></span>Live store data</span>}/>
 <div className="stats-grid">
  <Stat label="Sales today" value={currency(store,todaySales.reduce((a,s)=>a+s.total,0))} detail={`${todaySales.length} transactions`} icon={CircleDollarSign} accent="deep"/>
  <Stat label="Products on hand" value={String(store.products.length)} detail={`${store.products.reduce((a,p)=>a+p.quantity,0).toLocaleString()} units across shelves`} icon={Package}/>
  <Stat label="Low-stock products" value={String(low.length)} detail="At or below minimum level" icon={ArrowDownLeft} accent="amber"/>
  <Stat label="Inventory at cost" value={currency(store,inventoryValue)} detail={`${store.products.filter(p=>p.quantity===0).length} items out of stock`} icon={Boxes} accent="blue"/>
  <Stat label="Transactions today" value={String(todaySales.length)} detail="Completed at the counter" icon={ShoppingCart}/>
  <Stat label="Expiring soon" value={String(expiring.length)} detail={`Within ${store.settings.expiryDays} days`} icon={Clock3} accent="amber"/>
  <Stat label="Out of stock" value={String(store.products.filter(p=>p.quantity===0).length)} detail="Unavailable on shelf" icon={AlertTriangle} accent="red"/>
  <Stat label="Revenue this month" value={currency(store,valid.filter(s=>new Date(s.timestamp).getMonth()===new Date().getMonth()&&new Date(s.timestamp).getFullYear()===new Date().getFullYear()).reduce((a,s)=>a+s.total,0))} detail="Completed sales" icon={BarChart3} accent="deep"/>
 </div>
 <div className="dashboard-grid">
  <Panel title="Sales overview" sub="Completed sales · selected period" className="sales-chart" action={<div className="segmented">{[1,7,30].map(n=><button key={n} onClick={()=>setRange(n)} className={range===n?'selected':''}>{n===1?'Today':`${n} days`}</button>)}</div>}>
   <div className="chart-summary"><strong>{currency(store,salesRange.reduce((a,s)=>a+s.total,0))}</strong><span><ArrowUpRight size={14}/> All completed transactions</span></div>
   <div className="chart-bars" data-testid="chart-sales">{chart.map((b,i)=><div className="chart-column" key={`${b.label}-${i}`}><div className="bar-track"><div className={`bar ${i===chart.length-1?'current':''}`} style={{height:`${Math.max(b.total?8:3,b.total/chartMax*100)}%`}} title={currency(store,b.total)} /></div><small>{b.label}</small></div>)}</div>
  </Panel>
  <Panel title="Needs a closer look" sub="A quick read of your shelves">
    {low.length===0&&expiring.length===0&&expired.length===0?<Empty title="Shelves are in good shape" sub="No low-stock, expired or near-expiry medicines."/>:<div className="alert-list">{low.slice(0,3).map(p=><div className="alert-row" key={p.id}><span className="alert-symbol low"><ArrowDownLeft size={15}/></span><div><b>{p.name}</b><small>{p.quantity===0?'Out of stock':`${p.quantity} ${p.unit}s left · min ${p.minStock}`}</small></div><Badge tone={p.quantity===0?'red':'amber'}>{p.quantity===0?'Out':'Low'}</Badge></div>)}{expiring.slice(0,2).map(p=><div className="alert-row" key={p.id}><span className="alert-symbol expire"><Clock3 size={15}/></span><div><b>{p.name}</b><small>Expires {dateLabel(p.expiryDate)}</small></div><Badge tone="amber">Expiry</Badge></div>)}{expired.slice(0,2).map(p=><div className="alert-row" key={p.id}><span className="alert-symbol expire"><AlertTriangle size={15}/></span><div><b>{p.name}</b><small>Expired {dateLabel(p.expiryDate)} · remove from shelf</small></div><Badge tone="red">Expired</Badge></div>)}</div>}
  </Panel>
  <Panel title="Best sellers" sub="By units sold · all completed sales" action={<Link className="text-link" href="/reports">Full report <ChevronRight size={14}/></Link>}>
   {top.length===0?<Empty title="No sales recorded yet" sub="Completed sales will appear here."/>:<div className="seller-list">{top.map((item,i)=><div className="seller-row" key={item.product}><span className={`rank rank-${i+1}`}>{String(i+1).padStart(2,'0')}</span><div className="seller-name"><b>{item.product}</b><small>{item.qty} units moved</small></div><strong>{currency(store,item.revenue)}</strong></div>)}</div>}
  </Panel>
  <Panel title="Recent transactions" sub="The latest from your counter" action={<Link className="text-link" href="/sales">View all <ChevronRight size={14}/></Link>} className="transactions-panel">
   <div className="table-wrap"><table><thead><tr><th>INVOICE</th><th>CUSTOMER</th><th>WHEN</th><th>AMOUNT</th><th>PAYMENT</th><th>STATUS</th></tr></thead><tbody>{store.sales.slice(0,5).map(s=><tr key={s.id}><td className="mono">{s.invoice}</td><td>{s.customer}</td><td>{new Date(s.timestamp).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</td><td className="strong-cell">{currency(store,s.total)}</td><td>{s.payment}</td><td><Badge tone={s.status==='Completed'?'green':'red'}>{s.status}</Badge></td></tr>)}</tbody></table></div>
  </Panel>
 </div></>;
}

function Products({store,saveProduct,deleteRecord}:Shared){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All categories'),[page,setPage]=useState(1),[modal,setModal]=useState<Product|null|false>(false),[detail,setDetail]=useState<Product|null>(null);
 const [sort,setSort]=useState('name');
 const filtered=store.products.filter(p=>(`${p.name} ${p.genericName} ${p.sku} ${p.brand}`.toLowerCase().includes(query.toLowerCase()))&&(category==='All categories'||p.category===category)).sort((a,b)=>{const av=a[sort as keyof Product],bv=b[sort as keyof Product];return typeof av==='number'&&typeof bv==='number'?av-bv:String(av||'').localeCompare(String(bv||''))});
 const pageSize=7, pages=Math.max(1,Math.ceil(filtered.length/pageSize)), shown=filtered.slice((page-1)*pageSize,page*pageSize);
 const categories=[...new Set(store.products.map(p=>p.category))];
 return <><Heading eyebrow="MEDICINE CATALOG" title="Products" description="Your complete medicine catalog, with stock and expiry at a glance." action={<Button onClick={()=>setModal(null)} icon={<Plus size={16}/>}>Add medicine</Button>}/>
  <div className="mini-metrics"><span><b>{store.products.length}</b> listed</span><span><b>{store.products.filter(p=>p.quantity<=p.minStock).length}</b> need replenishment</span><span><b>{store.products.filter(p=>statusOf(p,store.settings.expiryDays)==='Expiring soon').length}</b> expiring soon</span></div>
  <Panel title="Medicine catalog" sub={`${filtered.length} records`} className="list-panel">
   <div className="toolbar"><SearchBox value={query} onChange={v=>{setQuery(v);setPage(1)}} placeholder="Search name, brand, SKU..."/><label className="select-wrap"><ListFilter size={15}/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option>All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label><label className="select-wrap sort-wrap"><SlidersHorizontal size={15}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort: name</option><option value="quantity">Sort: stock</option><option value="expiryDate">Sort: expiry</option><option value="sellingPrice">Sort: price</option></select></label></div>
   <div className="table-wrap"><table><thead><tr><th>MEDICINE</th><th>SKU / BATCH</th><th>CATEGORY</th><th>STOCK</th><th>SELL PRICE</th><th>EXPIRY</th><th>STATUS</th><th></th></tr></thead><tbody>{shown.map(p=>{const status=statusOf(p,store.settings.expiryDays);return <tr key={p.id}><td><button className="product-link" onClick={()=>setDetail(p)}><b>{p.name}</b><small>{p.genericName} · {p.strength}</small></button></td><td><span className="mono">{p.sku}</span><small className="subcell">{p.batchNumber}</small></td><td>{p.category}</td><td><b>{p.quantity}</b><small className="subcell">{p.unit}s</small></td><td>{currency(store,p.sellingPrice)}</td><td>{dateLabel(p.expiryDate)}</td><td><Badge tone={status==='In stock'?'green':status==='Low stock'||status==='Expiring soon'?'amber':'red'}>{status}</Badge></td><td><button className="tiny-action" onClick={()=>setModal(p)} title="Edit"><MoreHorizontal size={17}/></button></td></tr>})}</tbody></table></div>
   {shown.length===0&&<Empty title="No medicines match" sub={query?'Try another search or category.':'Add your first medicine to build the catalog.'}/>}
   <Pagination page={page} pages={pages} count={filtered.length} size={pageSize} change={setPage}/>
  </Panel>
  {modal!==false&&<ProductModal initial={modal||undefined} suppliers={store.suppliers} onClose={()=>setModal(false)} onSave={p=>{saveProduct(p,!!modal);setModal(false)}}/>}
  {detail&&<ProductDetail product={detail} store={store} onClose={()=>setDetail(null)} onEdit={()=>{setModal(detail);setDetail(null)}} onDelete={()=>{deleteRecord('products',detail);setDetail(null)}}/>}
 </>;
}
function Pagination({page,pages,count,size,change}:{page:number;pages:number;count:number;size:number;change:(p:number)=>void}){return <div className="pagination"><span>Showing <b>{count?((page-1)*size+1):0}–{Math.min(page*size,count)}</b> of <b>{count}</b></span><div><button onClick={()=>change(Math.max(1,page-1))} disabled={page<=1} aria-label="Previous page"><ChevronLeft size={16}/></button><span>{page} / {pages}</span><button onClick={()=>change(Math.min(pages,page+1))} disabled={page>=pages} aria-label="Next page"><ChevronRight size={16}/></button></div></div>}
const productDefaults=():Product=>({id:id(),sku:`MED-${String(Date.now()).slice(-5)}`,name:'',genericName:'',brand:'',category:'Other',dosageForm:'Tablet',strength:'',unit:'tablet',barcode:'',batchNumber:'',supplierId:'',purchasePrice:0,sellingPrice:0,quantity:0,minStock:20,maxStock:100,manufactureDate:today(),expiryDate:days(365),prescriptionRequired:false,status:'Active',description:''});
function ProductModal({initial,suppliers,onClose,onSave}:{initial?:Product;suppliers:Supplier[];onClose:()=>void;onSave:(p:Product)=>void}){
 const [form,setForm]=useState<Product>(initial?{...initial}:productDefaults());
 const update=(key:keyof Product,value:any)=>setForm(f=>({...f,[key]:value}));
 const submit=(e:FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.sku.trim())return;onSave(form)};
 const textFields:[keyof Product,string][]=[['sku','SKU / product code'],['name','Product name'],['genericName','Generic name'],['brand','Brand'],['category','Category'],['dosageForm','Dosage form'],['strength','Strength'],['unit','Selling unit'],['barcode','Barcode'],['batchNumber','Batch number']];
 return <Modal title={initial?'Edit medicine':'Add a medicine'} subtitle="Keep the shelf record complete and accurate." onClose={onClose} wide><form onSubmit={submit}><div className="form-grid">{textFields.map(([key,label])=><Field key={key} label={label}><input required={key==='name'||key==='sku'} value={String(form[key]||'')} onChange={e=>update(key,e.target.value)}/></Field>)}<Field label="Supplier"><select value={form.supplierId} onChange={e=>update('supplierId',e.target.value)}><option value="">No supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{([['purchasePrice','Purchase price'],['sellingPrice','Selling price'],['quantity','Quantity on hand'],['minStock','Minimum stock'],['maxStock','Maximum stock']] as [keyof Product,string][]).map(([key,label])=><Field key={key} label={label}><input type="number" step={key.includes('Price')?'0.01':'1'} min="0" value={Number(form[key])} onChange={e=>update(key,Number(e.target.value))}/></Field>)}<Field label="Manufacture date"><input type="date" value={form.manufactureDate} onChange={e=>update('manufactureDate',e.target.value)}/></Field><Field label="Expiry date"><input type="date" value={form.expiryDate} onChange={e=>update('expiryDate',e.target.value)}/></Field><Field label="Status"><select value={form.status} onChange={e=>update('status',e.target.value)}><option>Active</option><option>Discontinued</option><option>On hold</option></select></Field><Field label="Prescription required"><select value={String(form.prescriptionRequired)} onChange={e=>update('prescriptionRequired',e.target.value==='true')}><option value="false">No</option><option value="true">Yes</option></select></Field><Field label="Description" full><textarea value={form.description} onChange={e=>update('description',e.target.value)} rows={2}/></Field></div><div className="modal-actions"><Button kind="quiet" onClick={onClose}>Cancel</Button><button className="button primary" type="submit"><Check size={16}/>{initial?'Save changes':'Add medicine'}</button></div></form></Modal>;
}
 function ProductDetail({product,store,onClose,onEdit,onDelete}:{product:Product;store:Store;onClose:()=>void;onEdit:()=>void;onDelete:()=>void}){const status=statusOf(product,store.settings.expiryDays);return <Modal title="Medicine details" subtitle={`${product.sku} · ${product.batchNumber}`} onClose={onClose}><div className="detail-title"><span className="medicine-tile"><PillIcon/></span><div><h3>{product.name}</h3><p>{product.genericName} · {product.brand}</p><Badge tone={status==='In stock'?'green':status==='Expired'||status==='Out of stock'?'red':'amber'}>{status}</Badge></div></div><div className="detail-grid">{[['Category',product.category],['Dosage / strength',`${product.dosageForm} · ${product.strength}`],['On hand',`${product.quantity} ${product.unit}s`],['Min / max',`${product.minStock} / ${product.maxStock}`],['Purchase price',currency(store,product.purchasePrice)],['Selling price',currency(store,product.sellingPrice)],['Barcode',product.barcode||'—'],['Supplier',store.suppliers.find(x=>x.id===product.supplierId)?.name||'—'],['Manufactured',dateLabel(product.manufactureDate)],['Expires',dateLabel(product.expiryDate)],['Prescription',product.prescriptionRequired?'Required':'Not required'],['Status',product.status]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div>{product.description&&<p className="detail-description">{product.description}</p>}<div className="modal-actions spread"><Button kind="danger" icon={<Trash2 size={15}/>} onClick={onDelete}>Delete</Button><div><Button kind="quiet" onClick={onClose}>Close</Button><Button onClick={onEdit}>Edit medicine</Button></div></div></Modal>}
function PillIcon(){return <Stethoscope size={20}/>}
function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){return <div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`modal-card ${wide?'wide':''}`}><div className="modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></div>{children}</div></div>}
function Field({label,children,full=false}:{label:string;children:ReactNode;full?:boolean}){return <label className={`field ${full?'full':''}`}><span>{label}</span>{children}</label>}
function Sales({store,completeSale,reverseSale,notify}:Shared){
 const [tab,setTab]=useState<'pos'|'history'>('pos'),[search,setSearch]=useState(''),[cart,setCart]=useState<Line[]>([]),[customer,setCustomer]=useState(store.customers.at(-1)?.id||''),[payment,setPayment]=useState('Card'),[filter,setFilter]=useState('');
  const matches=store.products.filter(p=>p.quantity>0&&p.status==='Active'&&statusOf(p,store.settings.expiryDays)!=='Expired'&&`${p.name} ${p.sku} ${p.barcode}`.toLowerCase().includes(search.toLowerCase())).slice(0,7);
 const add=(p:Product)=>{setCart(lines=>{const line=lines.find(x=>x.productId===p.id);if(line){if(line.qty>=p.quantity){notify('No more stock available');return lines;}return lines.map(x=>x.productId===p.id?{...x,qty:x.qty+1}:x)}return [...lines,{productId:p.id,name:p.name,qty:1,cost:p.purchasePrice,price:p.sellingPrice}]})};
 const updateQty=(pid:string,n:number)=>{const p=store.products.find(x=>x.id===pid);if(!p)return;setCart(lines=>n<=0?lines.filter(x=>x.productId!==pid):lines.map(x=>x.productId===pid?{...x,qty:Math.min(n,p.quantity)}:x))};
 const total=cart.reduce((a,x)=>a+x.price*x.qty,0);
 const filteredSales=store.sales.filter(s=>!filter||`${s.invoice} ${s.customer}`.toLowerCase().includes(filter.toLowerCase()));
 return <><Heading eyebrow="COUNTER & TRANSACTIONS" title="Sales" description="Ring up a customer or look back through the day’s transactions." action={<Button kind="outline" onClick={()=>setTab(tab==='pos'?'history':'pos')} icon={tab==='pos'?<FileClock size={16}/>:<ShoppingCart size={16}/>}>{tab==='pos'?'Sales history':'Open point of sale'}</Button>}/>
 <div className="sales-tabs"><button className={tab==='pos'?'active':''} onClick={()=>setTab('pos')}><ShoppingCart size={16}/> Point of sale</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><ClipboardList size={16}/> Sales history <span>{store.sales.length}</span></button></div>
 {tab==='pos'?<div className="pos-grid"><section className="panel catalog-panel"><div className="panel-head"><div><h2>Find medicine</h2><p>Search by name, product code or barcode.</p></div></div><SearchBox value={search} onChange={setSearch} placeholder="Start typing a medicine..."/><div className="pos-product-list">{matches.map(p=><button key={p.id} className="pos-product" onClick={()=>add(p)}><span className="medicine-tile"><PillIcon/></span><span className="pos-product-name"><b>{p.name}</b><small>{p.strength} · {p.quantity} in stock</small></span><strong>{currency(store,p.sellingPrice)}</strong><Plus size={17}/></button>)}</div>{matches.length===0&&<Empty title={search?'No matching medicines':'No medicines in stock'} sub={search?'Try a different name or SKU.':'Restock inventory before ringing up a sale.'}/>}</section>
  <section className="panel cart-panel"><div className="panel-head"><div><h2>Current sale</h2><p>{cart.reduce((a,x)=>a+x.qty,0)} items in basket</p></div><button className="text-button" onClick={()=>setCart([])} disabled={!cart.length}>Clear</button></div><Field label="Customer"><select value={customer} onChange={e=>setCustomer(e.target.value)}>{store.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><div className="cart-lines">{cart.map(line=><div className="cart-line" key={line.productId}><div><b>{line.name}</b><small>{currency(store,line.price)} each</small></div><div className="stepper"><button onClick={()=>updateQty(line.productId,line.qty-1)}>−</button><span>{line.qty}</span><button onClick={()=>updateQty(line.productId,line.qty+1)}>+</button></div><strong>{currency(store,line.qty*line.price)}</strong></div>)}{cart.length===0&&<div className="cart-empty"><ShoppingBag size={25}/><b>Your basket is empty</b><span>Add medicines from the catalog to start a sale.</span></div>}</div><Field label="Payment method"><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Card</option><option>Cash</option><option>Mobile payment</option><option>Insurance</option></select></Field><div className="checkout-total"><span>Subtotal</span><strong>{currency(store,total)}</strong></div><Button onClick={()=>{if(!cart.length){notify('Add at least one medicine first');return}completeSale(cart,customer,payment);setCart([])}} icon={<Check size={16}/>}>Complete sale · {currency(store,total)}</Button><small className="checkout-note"><ShieldCheck size={13}/> Stock updates as soon as the sale is completed.</small></section></div>
 :<Panel title="Sales history" sub={`${filteredSales.length} recorded transactions`}><div className="toolbar"><SearchBox value={filter} onChange={setFilter} placeholder="Find invoice or customer..."/></div><div className="table-wrap"><table><thead><tr><th>INVOICE</th><th>CUSTOMER</th><th>DATE & TIME</th><th>ITEMS</th><th>PAYMENT</th><th>TOTAL</th><th>STATUS</th><th></th></tr></thead><tbody>{filteredSales.map(s=><tr key={s.id}><td className="mono">{s.invoice}</td><td>{s.customer}</td><td>{new Date(s.timestamp).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</td><td>{s.items.reduce((a,x)=>a+x.qty,0)}</td><td>{s.payment}</td><td className="strong-cell">{currency(store,s.total)}</td><td><Badge tone={s.status==='Completed'?'green':'red'}>{s.status}</Badge></td><td>{s.status==='Completed'&&<button className="text-button danger-text" onClick={()=>reverseSale(s)}>Reverse</button>}</td></tr>)}</tbody></table></div>{filteredSales.length===0&&<Empty title="No transactions found" sub="Completed sales will appear in this ledger."/>}</Panel>}</>;
}
function Inventory({store,adjustStock}:Shared){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('All activity'),[adjust,setAdjust]=useState<Product|null>(null),[delta,setDelta]=useState(''),[note,setNote]=useState('');
 const movements=store.movements.filter(m=>`${m.product} ${m.reference} ${m.note}`.toLowerCase().includes(query.toLowerCase())&&(kind==='All activity'||m.kind===kind));
 const stock=store.products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase()));
 return <><Heading eyebrow="SHELF CONTROL" title="Inventory" description="On-hand quantities, replenishment signals and a complete movement audit." action={<span className="live-date"><Activity size={15}/> {store.movements.length} stock events</span>}/>
 <div className="stats-grid compact-stats"><Stat label="Units on hand" value={store.products.reduce((a,p)=>a+p.quantity,0).toLocaleString()} detail="Across active catalog" icon={Boxes}/><Stat label="Below minimum" value={String(store.products.filter(p=>p.quantity>0&&p.quantity<=p.minStock).length)} detail="Replenishment suggested" icon={ArrowDownLeft} accent="amber"/><Stat label="Out of stock" value={String(store.products.filter(p=>p.quantity===0).length)} detail="Unavailable on shelf" icon={AlertTriangle} accent="red"/><Stat label="Near expiry" value={String(store.products.filter(p=>statusOf(p,store.settings.expiryDays)==='Expiring soon').length)} detail={`Within ${store.settings.expiryDays} days`} icon={Clock3} accent="blue"/></div>
 <Panel title="Stock levels" sub={`${stock.length} medicines`}><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search stock..."/></div><div className="table-wrap"><table><thead><tr><th>MEDICINE</th><th>SKU</th><th>ON HAND</th><th>MINIMUM</th><th>STOCK COVER</th><th>STATUS</th><th></th></tr></thead><tbody>{stock.map(p=>{const state=statusOf(p,store.settings.expiryDays);return <tr key={p.id}><td><b>{p.name}</b><small className="subcell">{p.batchNumber}</small></td><td className="mono">{p.sku}</td><td><b>{p.quantity}</b> <small>{p.unit}s</small></td><td>{p.minStock}</td><td><div className="stock-meter"><span style={{width:`${Math.min(100,p.maxStock?100*p.quantity/p.maxStock:0)}%`}}/></div><small className="subcell">max {p.maxStock}</small></td><td><Badge tone={state==='In stock'?'green':state==='Low stock'||state==='Expiring soon'?'amber':'red'}>{state}</Badge></td><td><button className="button tiny outline" onClick={()=>{setAdjust(p);setDelta('');setNote('')}}>Adjust</button></td></tr>})}</tbody></table></div>{stock.length===0&&<Empty title="No stock records" sub="Try another search term."/>}</Panel>
 <Panel title="Movement history" sub="A signed audit trail of stock changes" className="movement-panel"><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search movement history..."/><label className="select-wrap"><Filter size={15}/><select value={kind} onChange={e=>setKind(e.target.value)}><option>All activity</option>{[...new Set(store.movements.map(m=>m.kind))].map(k=><option key={k}>{k}</option>)}</select><ChevronDown size={14}/></label></div><div className="table-wrap"><table><thead><tr><th>MEDICINE</th><th>CHANGE</th><th>TYPE</th><th>REFERENCE</th><th>DATE</th><th>NOTE</th></tr></thead><tbody>{movements.slice(0,12).map(m=><tr key={m.id}><td><b>{m.product}</b></td><td className={m.delta>0?'positive':'negative'}>{m.delta>0?'+':''}{m.delta}</td><td><Badge tone={m.delta>0?'green':m.kind==='Adjustment'?'amber':'neutral'}>{m.kind}</Badge></td><td className="mono">{m.reference}</td><td>{new Date(m.timestamp).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</td><td>{m.note}</td></tr>)}</tbody></table></div>{movements.length===0&&<Empty title="No movement yet" sub="Stock changes are recorded here automatically."/>}</Panel>
 {adjust&&<Modal title="Adjust stock" subtitle={`${adjust.name} · ${adjust.quantity} ${adjust.unit}s currently on hand`} onClose={()=>setAdjust(null)}><form onSubmit={e=>{e.preventDefault();const d=Number(delta);if(!d){return}adjustStock(adjust,d,note||'Manual count correction');setAdjust(null)}}><div className="form-grid"><Field label="Quantity change (+ to add, − to remove)"><input type="number" required value={delta} onChange={e=>setDelta(e.target.value)} placeholder="e.g. 12 or -3"/></Field><Field label="Reason"><select value={note} onChange={e=>setNote(e.target.value)}><option value="">Manual count correction</option><option>Damaged stock</option><option>Expired stock removed</option><option>Cycle count</option><option>Opening balance correction</option></select></Field></div><div className="modal-actions"><Button kind="quiet" onClick={()=>setAdjust(null)}>Cancel</Button><button type="submit" className="button primary"><Check size={15}/>Record adjustment</button></div></form></Modal>}
 </>;
}
function Purchases({store,patch,receivePurchase,notify}:Shared){
 const [search,setSearch]=useState(''),[modal,setModal]=useState(false),[supplierId,setSupplierId]=useState(store.suppliers[0]?.id||''),[productId,setProductId]=useState(store.products[0]?.id||''),[qty,setQty]=useState(''),[invoice,setInvoice]=useState('');
 const filtered=store.purchases.filter(p=>`${p.invoice} ${p.supplier}`.toLowerCase().includes(search.toLowerCase()));
 const create=(e:FormEvent)=>{e.preventDefault();const p=store.products.find(x=>x.id===productId),s=store.suppliers.find(x=>x.id===supplierId);const amount=Number(qty);if(!p||!s||amount<1)return;const item:Line={productId:p.id,name:p.name,qty:amount,cost:p.purchasePrice,price:p.sellingPrice};const record:Purchase={id:id(),invoice:invoice.trim()||`PO-${new Date().getFullYear()}-${String(store.purchases.length+183).padStart(4,'0')}`,supplierId:s.id,supplier:s.name,date:today(),status:'Pending',items:[item],total:amount*p.purchasePrice};patch('purchases',[record,...store.purchases]);setModal(false);setQty('');setInvoice('');notify('Purchase order created');};
 return <><Heading eyebrow="SUPPLIER ORDERS" title="Purchases" description="Track supplier orders from placement through receiving." action={<Button onClick={()=>setModal(true)} icon={<Plus size={16}/>}>New purchase</Button>}/><div className="stats-grid compact-stats"><Stat label="Purchase orders" value={String(store.purchases.length)} detail="All recorded orders" icon={ClipboardList}/><Stat label="Awaiting delivery" value={String(store.purchases.filter(p=>p.status==='Pending').length)} detail="Stock not yet received" icon={Clock3} accent="amber"/><Stat label="Received this month" value={String(store.purchases.filter(p=>p.status==='Received'&&new Date(p.date).getMonth()===new Date().getMonth()).length)} detail="Stock added to shelves" icon={PackageCheck} accent="deep"/><Stat label="Spend recorded" value={currency(store,store.purchases.reduce((a,p)=>a+p.total,0))} detail="Purchase cost" icon={CircleDollarSign} accent="blue"/></div>
 <Panel title="Order ledger" sub={`${filtered.length} purchase records`}><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search PO or supplier..."/></div><div className="table-wrap"><table><thead><tr><th>PURCHASE ORDER</th><th>SUPPLIER</th><th>ORDER DATE</th><th>LINES</th><th>AMOUNT</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td className="mono">{p.invoice}</td><td><b>{p.supplier}</b></td><td>{dateLabel(p.date)}</td><td>{p.items.length}</td><td className="strong-cell">{currency(store,p.total)}</td><td><Badge tone={p.status==='Received'?'green':'amber'}>{p.status}</Badge></td><td>{p.status==='Pending'?<button className="button tiny primary" onClick={()=>receivePurchase(p)}>Receive stock</button>:<span className="quiet-text">Complete</span>}</td></tr>)}</tbody></table></div>{filtered.length===0&&<Empty title="No purchase orders yet" sub="Create an order to track supplier deliveries." action={<Button onClick={()=>setModal(true)} icon={<Plus size={15}/>}>New purchase</Button>}/>}</Panel>
 {modal&&<Modal title="Create purchase order" subtitle="Add a line to a supplier order. Stock is added when received." onClose={()=>setModal(false)}><form onSubmit={create}><div className="form-grid"><Field label="Supplier"><select value={supplierId} onChange={e=>setSupplierId(e.target.value)}>{store.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Invoice / PO number"><input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="Auto-generated if blank"/></Field><Field label="Medicine"><select value={productId} onChange={e=>setProductId(e.target.value)}>{store.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Order quantity"><input type="number" min="1" required value={qty} onChange={e=>setQty(e.target.value)} placeholder="Units"/></Field></div><div className="modal-actions"><Button kind="quiet" onClick={()=>setModal(false)}>Cancel</Button><button className="button primary" type="submit"><FilePlus2 size={15}/>Create order</button></div></form></Modal>}</>;
}
type Kind='customers'|'suppliers'|'staff';
function Directory({store,saveEntity,deleteRecord,kind}:Shared&{kind:Kind}){
 const [search,setSearch]=useState(''),[modal,setModal]=useState<any>(false);
 const titles={customers:['CUSTOMER RELATIONSHIPS','Customers','A familiar face makes a better pharmacy. Keep useful details close.'],suppliers:['SUPPLY NETWORK','Suppliers','The partners who keep your shelves dependable.'],staff:['THE PHARMACY TEAM','Staff','Manage your local team roster and contact details.']} as const;
 const [eyebrow,title,description]=titles[kind];const list=store[kind] as any[];
 const filtered=list.filter(x=>Object.values(x).join(' ').toLowerCase().includes(search.toLowerCase()));
 const fields=kind==='customers'?[['name','Full name'],['phone','Phone'],['email','Email'],['address','Neighborhood / address'],['loyalty','Loyalty points']]:kind==='suppliers'?[['name','Supplier name'],['contact','Account contact'],['phone','Phone'],['email','Email'],['address','Location'],['terms','Payment terms']]:[['name','Full name'],['role','Role'],['phone','Phone'],['email','Email'],['status','Shift status']];
 const fresh=()=>kind==='customers'?{id:id(),name:'',phone:'',email:'',address:'',loyalty:0,createdAt:today()}:kind==='suppliers'?{id:id(),name:'',contact:'',phone:'',email:'',address:'',terms:'Net 30'}:{id:id(),name:'',role:'Pharmacy technician',phone:'',email:'',status:'On shift'};
 return <><Heading eyebrow={eyebrow} title={title} description={description} action={<Button onClick={()=>setModal({...fresh(),_editing:false})} icon={<Plus size={16}/>}>Add {kind==='staff'?'staff member':kind.slice(0,-1)}</Button>}/><div className="stats-grid compact-stats"><Stat label={`Total ${kind}`} value={String(list.length)} detail="Saved in this browser" icon={kind==='staff'?ShieldCheck:kind==='suppliers'?Truck:Users}/><Stat label={kind==='customers'?'Loyalty points':'Current records'} value={kind==='customers'?String(list.reduce((a,x)=>a+(Number(x.loyalty)||0),0)):String(list.length)} detail={kind==='staff'?`${list.filter(x=>x.status==='On shift').length} on shift`:kind==='suppliers'?'Trusted supply partners':'Across all customers'} icon={kind==='staff'?Activity:kind==='suppliers'?BriefcaseMedical:Sparkles} accent="deep"/><Stat label={kind==='customers'?'Added this month':kind==='staff'?'On shift':'Net 30 terms'} value={kind==='customers'?String(list.filter(x=>new Date(x.createdAt)>new Date(Date.now()-30*86400000)).length):kind==='staff'?String(list.filter(x=>x.status==='On shift').length):String(list.filter(x=>x.terms==='Net 30').length)} detail={kind==='staff'?'Ready for today':'Current roster snapshot'} icon={kind==='staff'?Clock3:CalendarDays} accent="amber"/></div>
 <Panel title={`${kind[0].toUpperCase()+kind.slice(1)} directory`} sub={`${filtered.length} records`}><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder={`Search ${kind}...`}/></div><div className="table-wrap"><table><thead><tr>{fields.map(([key,label])=><th key={key}>{key==='name'?'NAME':label.toUpperCase()}</th>)}<th>ADDED</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}>{fields.map(([key])=><td key={key}>{key==='name'?<div className="person-cell"><span className="avatar soft">{item.name.split(' ').map((p:string)=>p[0]).slice(0,2).join('')}</span><b>{item.name}</b></div>:key==='email'?<span className="email-cell">{item[key]}</span>:key==='loyalty'?`${item[key]} pts`:key==='status'?<Badge tone={item.status==='On shift'?'green':'neutral'}>{item[key]}</Badge>:item[key]||'—'}</td>)}<td>{kind==='customers'?dateLabel(item.createdAt):'—'}</td><td><div className="row-actions"><button className="tiny-action" onClick={()=>setModal({...item,_editing:true})} title="Edit"><MoreHorizontal size={17}/></button><button className="tiny-action danger-hover" onClick={()=>deleteRecord(kind,item)} title="Delete"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>{filtered.length===0&&<Empty title={`No ${kind} found`} sub={search?'Try another search.':`Add a ${kind==='staff'?'team member':kind.slice(0,-1)} to get started.`}/>}</Panel>
 {modal!==false&&<Modal title={modal._editing?'Edit record':`Add ${kind==='staff'?'staff member':kind.slice(0,-1)}`} subtitle="Changes are stored locally in this browser." onClose={()=>setModal(false)}><form onSubmit={e=>{e.preventDefault();const editing=!!modal._editing;const {_editing,...item}=modal;saveEntity(kind,item,editing);setModal(false)}}><div className="form-grid">{fields.map(([key,label])=><Field key={key} label={label}><input required={key==='name'} type={key==='email'?'email':key==='loyalty'?'number':'text'} value={modal[key]||''} onChange={e=>setModal((old:any)=>({...old,[key]:key==='loyalty'?Number(e.target.value):e.target.value}))}/></Field>)}</div><div className="modal-actions"><Button kind="quiet" onClick={()=>setModal(false)}>Cancel</Button><button type="submit" className="button primary"><Check size={15}/>{modal._editing?'Save changes':'Add record'}</button></div></form></Modal>}</>;
}
function Reports({store}:Shared){
 const [period,setPeriod]=useState(30);
 const sales=store.sales.filter(s=>s.status==='Completed'&&(Date.now()-new Date(s.timestamp).getTime())/86400000<period);
 const revenue=sales.reduce((a,s)=>a+s.total,0),cogs=sales.reduce((a,s)=>a+s.items.reduce((b,i)=>b+i.cost*i.qty,0),0);
 const productTotals=new Map<string,{qty:number;revenue:number;cost:number}>();sales.forEach(s=>s.items.forEach(i=>{const x=productTotals.get(i.productId)||{qty:0,revenue:0,cost:0};x.qty+=i.qty;x.revenue+=i.qty*i.price;x.cost+=i.qty*i.cost;productTotals.set(i.productId,x)}));
 const products=[...productTotals].map(([pid,v])=>({name:store.products.find(p=>p.id===pid)?.name||'Removed medicine',...v,margin:v.revenue-v.cost})).sort((a,b)=>b.revenue-a.revenue);
 const purchaseSpend=store.purchases.filter(p=>(Date.now()-new Date(p.date).getTime())/86400000<period).reduce((a,p)=>a+p.total,0);
 return <><Heading eyebrow="BUSINESS PULSE" title="Reports" description="A practical read on what’s moving, what it costs and where to look next." action={<label className="select-wrap"><CalendarDays size={15}/><select value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={1}>Today</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={365}>Last 12 months</option></select><ChevronDown size={14}/></label>}/><div className="stats-grid"><Stat label="Gross sales" value={currency(store,revenue)} detail={`${sales.length} completed transactions`} icon={CircleDollarSign} accent="deep"/><Stat label="Estimated gross profit" value={currency(store,revenue-cogs)} detail={`${revenue?((revenue-cogs)/revenue*100).toFixed(1):'0.0'}% margin on sales`} icon={BarChart3}/><Stat label="Product cost of goods" value={currency(store,cogs)} detail="Captured cost at sale time" icon={Package}/><Stat label="Supplier spend" value={currency(store,purchaseSpend)} detail="Orders within period" icon={Truck} accent="amber"/></div>
 <div className="dashboard-grid report-grid"><Panel title="Revenue & margin by product" sub={`Top medicines · past ${period===1?'day':period===365?'year':`${period} days`}`} className="transactions-panel"><div className="table-wrap"><table><thead><tr><th>MEDICINE</th><th>UNITS SOLD</th><th>REVENUE</th><th>PRODUCT COST</th><th>GROSS PROFIT</th></tr></thead><tbody>{products.map((p,i)=><tr key={p.name}><td><div className="person-cell"><span className={`rank rank-${i+1}`}>{String(i+1).padStart(2,'0')}</span><b>{p.name}</b></div></td><td>{p.qty}</td><td>{currency(store,p.revenue)}</td><td>{currency(store,p.cost)}</td><td className="positive">{currency(store,p.margin)}</td></tr>)}</tbody></table></div>{products.length===0&&<Empty title="No sales in this period" sub="Sales reports update when a transaction is completed."/>}</Panel><Panel title="Inventory exposure" sub="Value at recorded purchase cost"><div className="exposure-number">{currency(store,store.products.reduce((a,p)=>a+p.quantity*p.purchasePrice,0))}</div><div className="exposure-list">{[['On shelf',store.products.filter(p=>p.quantity>0).length,'green'],['Low stock',store.products.filter(p=>p.quantity>0&&p.quantity<=p.minStock).length,'amber'],['Out of stock',store.products.filter(p=>p.quantity===0).length,'red'],['Expiring soon',store.products.filter(p=>statusOf(p,store.settings.expiryDays)==='Expiring soon').length,'blue']].map(([label,value,tone])=><div key={String(label)}><span className={`dot ${tone}`}/><span>{label}</span><b>{value}</b></div>)}</div></Panel></div>
 <Panel title="Transactions in period" sub="Completed sales included in this report"><div className="table-wrap"><table><thead><tr><th>INVOICE</th><th>CUSTOMER</th><th>DATE</th><th>PAYMENT</th><th>SALES</th><th>COST</th><th>MARGIN</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td className="mono">{s.invoice}</td><td>{s.customer}</td><td>{dateLabel(s.timestamp)}</td><td>{s.payment}</td><td>{currency(store,s.total)}</td><td>{currency(store,s.items.reduce((a,i)=>a+i.cost*i.qty,0))}</td><td className="positive">{currency(store,s.total-s.items.reduce((a,i)=>a+i.cost*i.qty,0))}</td></tr>)}</tbody></table></div>{sales.length===0&&<Empty title="Nothing to report yet" sub="Complete a sale to start building your reports."/ >}</Panel></>;
}
function SettingsPage({store,patch,notify}:Shared){
 const [draft,setDraft]=useState(store.settings);
 useEffect(()=>setDraft(store.settings),[store.settings]);
 const save=(e:FormEvent)=>{e.preventDefault();patch('settings',draft);notify('Pharmacy settings saved')};
 const exportData=()=>{const blob=new Blob([JSON.stringify({version:1,data:store},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='harbor-pine-pharmacy-backup.json';link.click();URL.revokeObjectURL(link.href);};
 const restore=()=>{const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=()=>{const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));const d=parsed.data;if(!d||!Array.isArray(d.products)||!Array.isArray(d.sales))throw new Error();if(!window.confirm('Replace all locally stored pharmacy data with this backup?'))return;for(const k of ['products','customers','suppliers','staff','sales','purchases','movements','settings'])if(d[k]===undefined)throw new Error();localStorage.setItem(KEY,JSON.stringify({version:1,data:d}));window.location.reload()}catch{notify('This backup file is invalid. Current data is unchanged.')}};reader.readAsText(file)};input.click();};
 return <><Heading eyebrow="LOCAL CONFIGURATION" title="Settings" description="Tune how Harbor & Pine appears and how shelf alerts are calculated."/><div className="settings-layout"><Panel title="Pharmacy profile" sub="Details used throughout your workspace"><form onSubmit={save}><div className="form-grid"><Field label="Pharmacy name" full><input value={draft.pharmacyName} onChange={e=>setDraft({...draft,pharmacyName:e.target.value})}/></Field><Field label="Address" full><input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></Field><Field label="Phone"><input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></Field><Field label="Currency"><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option value="USD">USD · US Dollar</option><option value="CAD">CAD · Canadian Dollar</option><option value="GBP">GBP · Pound sterling</option><option value="EUR">EUR · Euro</option></select></Field><Field label="Default sales tax (%)"><input type="number" min="0" max="100" step=".1" value={draft.tax} onChange={e=>setDraft({...draft,tax:Number(e.target.value)})}/></Field><Field label="Low-stock threshold"><input type="number" min="0" value={draft.lowStock} onChange={e=>setDraft({...draft,lowStock:Number(e.target.value)})}/></Field><Field label="Expiry alert window (days)"><input type="number" min="1" value={draft.expiryDays} onChange={e=>setDraft({...draft,expiryDays:Number(e.target.value)})}/></Field></div><div className="modal-actions left"><button className="button primary" type="submit"><Check size={15}/>Save settings</button></div></form></Panel><div className="settings-side"><Panel title="Browser data" sub="This workspace runs entirely on this device."><div className="local-note"><span><ShieldCheck size={18}/></span><b>Private by default</b><p>Pharmacy records are stored in this browser only. No account, server or third-party service is involved.</p></div><div className="data-actions"><Button kind="outline" onClick={exportData} icon={<ArrowDownLeft size={15}/>}>Export data backup</Button><Button kind="quiet" onClick={restore} icon={<ArrowUpRight size={15}/>}>Restore from backup</Button></div><div className="data-count">{store.products.length} medicines <span>·</span> {store.sales.length} sales <span>·</span> {store.customers.length} customers</div></Panel><Panel title="Workspace notes" sub="A few things to keep in mind"><div className="note-list"><p><Check size={15}/> Sales capture unit cost and selling price at transaction time.</p><p><Check size={15}/> Reversing a sale restores shelf stock and keeps an audit trail.</p><p><Check size={15}/> Expiry and low-stock labels update from current product data.</p></div></Panel></div></div></>;
}
function NotFound(){return <div className="not-found"><span className="empty-icon"><Search size={23}/></span><div className="eyebrow">WRONG AISLE</div><h1>We can’t find that page.</h1><p>The page may have moved, or the link may be out of date.</p><Link href="/" className="button primary">Back to overview</Link></div>}

function App(){return <WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/,'')}><PharmacyApp/></WouterRouter>}
export default App;